#version: '3.8'
#
#services:
#
#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    ports:
#      - "8080:80"
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./nginx/html:/usr/share/nginx/html:ro
#    networks:
#      - stress-net
#    depends_on:
#      - backend
#
#  backend:
#    build:
#      context: ./backend
#    container_name: backend
#    ports:
#      - "8081:8081"
#    networks:
#      - stress-net
#
#  locust:
#    image: locustio/locust
#    container_name: locust-runner
#    volumes:
#      - ./load-test:/mnt/locust
#    ports:
#      - "8089:8089"
#    working_dir: /mnt/locust
#    command: >
#      -f locustfile.py --headless -u 1000 -r 100 --run-time 1m --host=http://nginx
#    networks:
#      - stress-net
#
#networks:
#  stress-net:
#    driver: bridge

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8081:8081"
    networks:
      - stress-net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    networks:
      - stress-net
    depends_on:
      - backend

  locust:
    image: locustio/locust
    container_name: locust-runner
    volumes:
      - ./load-test:/mnt/locust
    ports:
      - "8089:8089"
    working_dir: /mnt/locust
    command: >
      -f locustfile.py --host=http://nginx
    networks:
      - stress-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - stress-net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.0
    container_name: logstash
    ports:
      - "5001:5001"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    networks:
      - stress-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - stress-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - stress-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - stress-net



networks:
  stress-net:
    driver: bridge
